import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/Header";
import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";
import { UserContextProvider } from "@/helper/userContext";
import { connectWithdb } from "@/helper/dbConnection";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  connectWithdb()

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserContextProvider>
          <Toaster></Toaster>
          <div>
            <Header></Header>
          </div>
          {children}
          <div>
            <Footer></Footer>
          </div>
        </UserContextProvider>
      </body>
    </html>
  );
}
